name: Build GodMode9i

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}
      author_name: ${{ steps.build.outputs.author_name }}
      committer_name: ${{ steps.build.outputs.committer_name }}
      commit_subject: ${{ steps.build.outputs.commit_subject }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install p7zip-full -y
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Build & Package GodMode9i
        id: build
        run: |
          make all dsi
          chmod +x make_cia
          ./make_cia --srl="GodMode9i.dsi" --id_0=$(git rev-parse --short=7 HEAD) --tikID=$(git rev-parse --short=16 HEAD)
          mkdir GodMode9i/
          cp GodMode9i.dsi GodMode9i/
          cp GodMode9i.nds GodMode9i/
          cp GodMode9i.cia GodMode9i/
          7z a GodMode9i.7z GodMode9i/

          mkdir -p ~/artifacts
          cp GodMode9i.dsi ~/artifacts
          cp GodMode9i.nds ~/artifacts
          cp GodMode9i.cia ~/artifacts
          cp GodMode9i.7z ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v3
        with:
          path: ~/artifacts/*
          name: build
